### ISSUE TITLE
GPLv3 License

### ISSUE THREAD

**Issue by cbc02009** [PrintersForAnts/Baby-Legacy#1]
Hi! very cool project you have! Don't forget that because it's derived from Voron printers you must include a copy of the GPLv3 license in your repo.

Good luck with the project!

**Comment by Super6b** [comment]
---Original---
From: ***@***.***&gt;
Date: Tue, Feb 8, 2022 04:46 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Super6b/Baby-Legacy] GPLv3 License (Issue #1)




 
Hi! very cool project you have! Don't forget that because it's derived from Voron printers you must include a copy of the GPLv3 license in your repo.
 
Good luck with the project!

**Comment by Super6b** [comment]
get it, thanks.



---Original---
From: ***@***.***&gt;
Date: Tue, Feb 8, 2022 04:46 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Super6b/Baby-Legacy] GPLv3 License (Issue #1)




 
Hi! very cool project you have! Don't forget that because it's derived from Voron printers you must include a copy of the GPLv3 license in your repo.
 
Good luck with the project!
